# pyright: reportMissingModuleSource=false
from __future__ import annotations

import enum
from typing import *

if TYPE_CHECKING:
    # fix some namespace issues for submodules
    import hou
    import hou.anonstats

def __init__(*args: Any, **kwargs: Any): ...
def recordOccurrence(key: str) -> None: ...
def recordString(key: str, value: str) -> None: ...
def hasString(key: str) -> bool: ...
def getString(key: str) -> str: ...
def incrementCount(key: str, count: int = 1) -> None: ...
def logEvent(key: str, message: str) -> None: ...
def addSum(key: str, stat_value: float, count: int = 1) -> None: ...
